version: '3.8'

services:
  wordpress:
    # image: wordpress:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wp-dev
    depends_on:
      - db
    networks:
      - wp_network
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA}
      # WordPress initial setup configuration
      WORDPRESS_TITLE: ${WORDPRESS_TITLE:-WordPress Development Site}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER:-admin}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD:-admin}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL:-admin@example.com}
      WORDPRESS_LOCALE: ${WORDPRESS_LOCALE:-en_US}
    volumes:
      - wordpress_data:/var/www/html
      - ${PLUGIN_SRC_PATH}:/var/www/html/wp-content/plugins/${PLUGIN_DEST_NAME}   # 將 Plugin 挂載到 WordPress
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini           # 將 Xdebug 設定檔掛載到容器
      - ./logs:/var/dev-log
      
  db:
    image: mysql:5.7
    container_name: wp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp-dev-phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - "8181:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    networks:
      - wp_network

networks:
  wp_network:
    name: wp-dev-network

volumes:
  wordpress_data:
  db_data: